name: Large Weekly Spread
on:
  schedule:
    # At 00:00 on Wednesday and Sunday.
    - cron: "0 0 * * WED,SUN"

  workflow_dispatch:
    inputs:
      snap_channel:
        description: "Snap Channel"
        default: "latest/edge"
      git_ref:
        description: "Git branch or ref"
        default: "main"

env:
  snap_channel: ${{ github.event.inputs.snap_channel || 'latest/edge' }}
  git_ref: ${{ github.event.inputs.git_ref || 'main' }}

jobs:
  pack-charm:
    runs-on: [spread-installed]
    strategy:
      fail-fast: false
      matrix:
        charm: [k8s-operator, operator, bundle, reactive]

    steps:
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout charmcraft
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.git_ref }}
          submodules: true
      - name: Download snap
        run: |
          snap download --channel="${{ env.snap_channel }}" charmcraft
      - name: Spread k8s operator
        run: |
          spread google:ubuntu-22.04-64:tests/spread/charms/${{ matrix.charm }}
